// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillManager.Infrastructure.Identity.AppDbContext;

#nullable disable

namespace SkillManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024054750_SecondCreate")]
    partial class SecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillManager.Domain.Entities.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SuiteId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SuiteId");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.ApplicationSkill", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId", "SkillId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("SkillId");

                    b.ToTable("ApplicationSkills", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.ApplicationSuite", b =>
                {
                    b.Property<int>("SuiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuiteId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Perimeter")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SuiteId");

                    b.ToTable("ApplicationSuites", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryTypeId");

                    b.HasIndex("Name");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryTypeId = 2,
                            Name = "CONNAISSANCES METIER"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryTypeId = 2,
                            Name = "CONCEPTION SOLUTION SI"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryTypeId = 1,
                            Name = "CONNAISSANCE APPLI AMC"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryTypeId = 1,
                            Name = "TECHNIQUES DE PROGRAMMATION"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            Name = "GESTION DE PROJET"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            Name = "AUTRES COMPETENCES"
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.CategoryType", b =>
                {
                    b.Property<int>("CategoryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryTypeId");

                    b.ToTable("CategoryTypes");

                    b.HasData(
                        new
                        {
                            CategoryTypeId = 1,
                            Name = "Technical"
                        },
                        new
                        {
                            CategoryTypeId = 2,
                            Name = "Functional"
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("LevelId");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            Name = "Notion",
                            Points = 1
                        },
                        new
                        {
                            LevelId = 2,
                            Name = "Pratique",
                            Points = 2
                        },
                        new
                        {
                            LevelId = 3,
                            Name = "Maitrise",
                            Points = 3
                        },
                        new
                        {
                            LevelId = 4,
                            Name = "Expert",
                            Points = 4
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CriticalityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstLevelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FourthLevelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ProjectRequiresSkill")
                        .HasColumnType("bit");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<string>("SecondLevelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ThirdLevelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            SubCategoryId = 1,
                            CategoryId = 1,
                            Name = "Finance"
                        },
                        new
                        {
                            SubCategoryId = 2,
                            CategoryId = 2,
                            Name = "01-Cadrage"
                        },
                        new
                        {
                            SubCategoryId = 3,
                            CategoryId = 2,
                            Name = "02-Design"
                        },
                        new
                        {
                            SubCategoryId = 4,
                            CategoryId = 2,
                            Name = "02-Design fonctionnel"
                        },
                        new
                        {
                            SubCategoryId = 5,
                            CategoryId = 2,
                            Name = "02-Design technique"
                        },
                        new
                        {
                            SubCategoryId = 6,
                            CategoryId = 2,
                            Name = "03-Data"
                        },
                        new
                        {
                            SubCategoryId = 7,
                            CategoryId = 2,
                            Name = "04-Analyse"
                        },
                        new
                        {
                            SubCategoryId = 8,
                            CategoryId = 2,
                            Name = "05-Testing"
                        },
                        new
                        {
                            SubCategoryId = 9,
                            CategoryId = 2,
                            Name = "06-Sécurité"
                        },
                        new
                        {
                            SubCategoryId = 10,
                            CategoryId = 3,
                            Name = "Outil Compta"
                        },
                        new
                        {
                            SubCategoryId = 11,
                            CategoryId = 3,
                            Name = "Outil CdG"
                        },
                        new
                        {
                            SubCategoryId = 12,
                            CategoryId = 3,
                            Name = "Outil Compta reglementaire"
                        },
                        new
                        {
                            SubCategoryId = 13,
                            CategoryId = 3,
                            Name = "Outil Conso"
                        },
                        new
                        {
                            SubCategoryId = 14,
                            CategoryId = 3,
                            Name = "Interprétation comptable"
                        },
                        new
                        {
                            SubCategoryId = 15,
                            CategoryId = 3,
                            Name = "Rapprochements"
                        },
                        new
                        {
                            SubCategoryId = 16,
                            CategoryId = 3,
                            Name = "Technique"
                        },
                        new
                        {
                            SubCategoryId = 17,
                            CategoryId = 4,
                            Name = "Langage de programmation"
                        },
                        new
                        {
                            SubCategoryId = 18,
                            CategoryId = 4,
                            Name = "Transfert de fichiers"
                        },
                        new
                        {
                            SubCategoryId = 19,
                            CategoryId = 4,
                            Name = "CI/CD"
                        },
                        new
                        {
                            SubCategoryId = 20,
                            CategoryId = 4,
                            Name = "Frameworks .NET"
                        },
                        new
                        {
                            SubCategoryId = 21,
                            CategoryId = 4,
                            Name = "Conso"
                        },
                        new
                        {
                            SubCategoryId = 22,
                            CategoryId = 4,
                            Name = "Scripting"
                        },
                        new
                        {
                            SubCategoryId = 23,
                            CategoryId = 4,
                            Name = "Front-End"
                        },
                        new
                        {
                            SubCategoryId = 24,
                            CategoryId = 4,
                            Name = "Middleware"
                        },
                        new
                        {
                            SubCategoryId = 25,
                            CategoryId = 4,
                            Name = "Gestion du code"
                        },
                        new
                        {
                            SubCategoryId = 26,
                            CategoryId = 4,
                            Name = "Base de données"
                        },
                        new
                        {
                            SubCategoryId = 27,
                            CategoryId = 4,
                            Name = "Testing"
                        },
                        new
                        {
                            SubCategoryId = 28,
                            CategoryId = 4,
                            Name = "Sécurité"
                        },
                        new
                        {
                            SubCategoryId = 29,
                            CategoryId = 4,
                            Name = "OS"
                        },
                        new
                        {
                            SubCategoryId = 30,
                            CategoryId = 4,
                            Name = "ETL"
                        },
                        new
                        {
                            SubCategoryId = 31,
                            CategoryId = 4,
                            Name = "Supervision / Monitoring"
                        },
                        new
                        {
                            SubCategoryId = 32,
                            CategoryId = 4,
                            Name = "Paramétrage progiciel"
                        },
                        new
                        {
                            SubCategoryId = 33,
                            CategoryId = 6,
                            Name = "Communication"
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Eid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Eid")
                        .IsUnique();

                    b.HasIndex("RefId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UtCode")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "TechLead"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserSME", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId", "CategoryTypeId");

                    b.HasIndex("CategoryTypeId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSMEs", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserSkill", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("LevelId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Application", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Category", "Category")
                        .WithMany("Applications")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.ApplicationSuite", "ApplicationSuite")
                        .WithMany("Applications")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationSuite");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.ApplicationSkill", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Application", "Application")
                        .WithMany("ApplicationSkills")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.Skill", "Skill")
                        .WithMany("ApplicationSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Category", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.CategoryType", "CategoryType")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryType");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Skill", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Category", "Category")
                        .WithMany("Skills")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.SubCategory", "SubCategory")
                        .WithMany("Skills")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.SubCategory", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.User", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserSME", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.CategoryType", "CategoryType")
                        .WithMany()
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.Skill", "Skill")
                        .WithMany("UserSMEs")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.User", "User")
                        .WithMany("UserSMEs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryType");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Level", "Level")
                        .WithMany("UserSkills")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Application", b =>
                {
                    b.Navigation("ApplicationSkills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.ApplicationSuite", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Category", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Skills");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.CategoryType", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Level", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Skill", b =>
                {
                    b.Navigation("ApplicationSkills");

                    b.Navigation("UserSMEs");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.SubCategory", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.User", b =>
                {
                    b.Navigation("UserSMEs");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
