// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillManager.Infrastructure.Identity.AppDbContext;

#nullable disable

namespace SkillManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillManager.Domain.Entities.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SuiteId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SuiteId");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.ApplicationSkill", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId", "SkillId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("SkillId");

                    b.ToTable("ApplicationSkills", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.ApplicationSuite", b =>
                {
                    b.Property<int>("SuiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuiteId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Perimeter")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SuiteId");

                    b.ToTable("ApplicationSuites", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryTypeId");

                    b.HasIndex("Name");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryTypeId = 2,
                            Name = "CONNAISSANCES METIER"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryTypeId = 1,
                            Name = "CONCEPTION SOLUTION SI"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryTypeId = 1,
                            Name = "CONNAISSANCE APPLI AMC"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryTypeId = 1,
                            Name = "TECHNIQUES DE PROGRAMMATION"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryTypeId = 2,
                            Name = "GESTION DE PROJET"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryTypeId = 2,
                            Name = "AUTRES COMPETENCES"
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.CategoryType", b =>
                {
                    b.Property<int>("CategoryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryTypeId");

                    b.ToTable("CategoryTypes");

                    b.HasData(
                        new
                        {
                            CategoryTypeId = 1,
                            Name = "Technical"
                        },
                        new
                        {
                            CategoryTypeId = 2,
                            Name = "Functional"
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("LevelId");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            Name = "Notion",
                            Points = 1
                        },
                        new
                        {
                            LevelId = 2,
                            Name = "Pratique",
                            Points = 2
                        },
                        new
                        {
                            LevelId = 3,
                            Name = "Maitrise",
                            Points = 3
                        },
                        new
                        {
                            LevelId = 4,
                            Name = "Expert",
                            Points = 4
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CriticalityLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstLevelDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FourthLevelDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ProjectRequiresSkill")
                        .HasColumnType("bit");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<string>("SecondLevelDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ThirdLevelDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("SkillId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            CategoryId = 1,
                            Code = "FCT-COMPTA-OPS",
                            CriticalityLevel = "P1",
                            FirstLevelDescription = "Connaissance des grands principes de la comptabilité des produits financiers, capacité à lire un bilan comptable, connaissance des grandes lignes d'un plan de compte d'une banque d'investissement.",
                            FourthLevelDescription = "Dépasse le niveau expérimenté. Connaissance des nouvelles réglementations comptables en lien avec les opérations de marché.",
                            Label = "Comptabilité des instruments financiers : Comptabilité des opérations de marché",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Connaissance des grands principes de la comptabilité des opérations de marché, Capacité à comptabiliser des opérations de marché selon les normes IAS39/IFRS9.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Expérimentée pour créer et /ou mettre à jour les spécifications fonctionnelles en lien avec les shémas comptables des produits financiers selon les normes IAS39/IFRS9."
                        },
                        new
                        {
                            SkillId = 2,
                            CategoryId = 1,
                            Code = "FCT-COMPTA-INTL",
                            CriticalityLevel = "P2",
                            FirstLevelDescription = "Dispose d'une connaissance théorique du Système d'Information comptable d'une banque internationale.",
                            FourthLevelDescription = "Sait faire le lien entre les fonctionnalités du SI Finance International et les processus de la Direction Financière de CACIB.",
                            Label = "Connaissance du système de Finance International de CACIB et de son architecture (fonctionnelle et applicative)",
                            ProjectRequiresSkill = true,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Connait l'architecture applicative du système d'information Finance International de CACIB.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Connait les fonctionnalités assurées par les différents composants applicatifs du SI Finance International de CACIB."
                        },
                        new
                        {
                            SkillId = 3,
                            CategoryId = 1,
                            Code = "FCT-RISQUES-ALM",
                            CriticalityLevel = "P2",
                            FirstLevelDescription = "Dispose d'une connaissance théorique du domaine des risques bancaires / de l'ALM.",
                            FourthLevelDescription = "Dispose d'une connaissance approfondie du monde des risques bancaire et une bonne connaissance du contexte CA-CIB (alimentation systèmes risques, organisation fonction risque…).",
                            Label = "Connaissance Risques / Ratios / ALM",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Dispose d'une connaissance approfondie du monde des risques bancaire et une connaissance générale de la gestion des risques par produit (opérations de marché et de financement en général).",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Dispose d'une connaissance approfondie du monde des risques bancaire et une bonne connaissance des impacts Risque sur les opérations de marché et de financement en général."
                        },
                        new
                        {
                            SkillId = 4,
                            CategoryId = 1,
                            Code = "FCT-CONSOLIDATION",
                            CriticalityLevel = "P2",
                            FirstLevelDescription = "Dispose d'une connaissance théorique du domaine de la Consolidation.",
                            FourthLevelDescription = "Connaissance avec précision de la Consolidation et peut évoluer en toute autonomie sur le sujet. Peut être considéré expert et mener une réflexion structurante chez le client.",
                            Label = "Connaissances conso",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Dispose d'une bonne connaissance de la Consolidation.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Dispose d'une connaissance précise de la Consolidation."
                        },
                        new
                        {
                            SkillId = 5,
                            CategoryId = 1,
                            Code = "FCT-FISCALITE",
                            CriticalityLevel = "P2",
                            FirstLevelDescription = "Dispose d'une connaissance théorique du domaine de la fiscalité.",
                            FourthLevelDescription = "Connaissance avec précision de la fiscalité et peut évoluer en toute autonomie sur le sujet. Peut être considéré expert et mener une réflexion structurante chez le client.",
                            Label = "Connaissances fiscalité : Base Fiscale, gestion TVA, Coeffficients de fiscalité, FEC, DES",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Dispose d'une bonne connaissance de la fiscalité.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Dispose d'une connaissance précise de la fiscalité."
                        },
                        new
                        {
                            SkillId = 6,
                            CategoryId = 1,
                            Code = "FCT-PROD-FRENCH",
                            CriticalityLevel = "P2",
                            FirstLevelDescription = "Dispose d'une connaissance théorique du domaine des Productions French.",
                            FourthLevelDescription = "Connaissance avec précision des Productions French et peut évoluer en toute autonomie sur le sujet. Peut être considéré expert et mener une réflexion structurante chez le client.",
                            Label = "Connaissances Productions French (ex : SURFI, PROTIDE, CRT/RPC)",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Dispose d'une bonne connaissance des Productions French.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Dispose d'une connaissance précise des Productions French."
                        },
                        new
                        {
                            SkillId = 7,
                            CategoryId = 1,
                            Code = "FCT-CONTROLE-GESTION",
                            CriticalityLevel = "P1",
                            FirstLevelDescription = "Dispose d'une connaissance théorique des campagnes budgétaires. Possède des notions théoriques sur les principaux concepts métiers et leur vocabulaire.",
                            FourthLevelDescription = "Être reconnu par ses pairs comme référent du domaine dans les groupes de travail.",
                            Label = "Connaissance du contrôle de gestion",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Savoir théorique approfondi mais peu mis en pratique ou mise en pratique sur un périmètre restreint.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Savoir théorique confronté à une mise en pratique concrète sur un périmètre large."
                        },
                        new
                        {
                            SkillId = 8,
                            CategoryId = 1,
                            Code = "FCT-MIGRATION-COMPTABLE",
                            CriticalityLevel = "P2",
                            FirstLevelDescription = "Comprendre les problématiques liés à une migration comptable.",
                            FourthLevelDescription = "Organiser, gérer et participer à une migration comptable avec des intervenants internes et externes à MAC.",
                            Label = "Organiser et gérer une migration comptable",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Participer à une migration comptable (en recette ou en production).",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Organiser une migration comptable avec des intervenants internes à MAC."
                        },
                        new
                        {
                            SkillId = 9,
                            CategoryId = 1,
                            Code = "FCT-MODELE-DONNEES",
                            CriticalityLevel = "P2",
                            FirstLevelDescription = "Dispose d'une connaissance théorique du Modèle de données comptable et réglementaire d'une Banque d'Investissement.",
                            FourthLevelDescription = "Sait faire le lien entre le Modèle de données et les différents reporting issus du système d'information Finance.",
                            Label = "Connaissance du modèle de données de la Finance",
                            ProjectRequiresSkill = true,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Connait les principales typologies de données utilisées par la Direction Financière de CACIB.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Connait le Modèle de Données Finance ainsi que les règles de calcul de ces données."
                        },
                        new
                        {
                            SkillId = 10,
                            CategoryId = 1,
                            Code = "FCT-PROCESSUS-DF",
                            CriticalityLevel = "P2",
                            FirstLevelDescription = "Dispose d'une connaissance théorique du mode d'organisation et des processus d'une fonction Finance dans un environnement bancaire.",
                            FourthLevelDescription = "Connait les \"pain points\" associés aux différents processus de la fonction Finance et liés à des dysfonctionnements du SI existant.",
                            Label = "Connaissance de l'organisation et des processus du métier Finance",
                            ProjectRequiresSkill = true,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Connait l'organisation générale de la Fonction Finance de CACIB, ainsi que ses principaux processus.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Connait de manière détaillée les processus du métier Finance de CACIB."
                        },
                        new
                        {
                            SkillId = 11,
                            CategoryId = 1,
                            Code = "FCT-PRODUITS-FINANCIERS",
                            CriticalityLevel = "P1",
                            FirstLevelDescription = "Dispose d'une connaissance théorique du domaine bancaire. Possède des notions théoriques sur les principaux concepts métiers et leur vocabulaire.",
                            FourthLevelDescription = "Dispose d'une connaissance approfondie du monde bancaire et une connaissance détaillée des opérations de marché et de financement.",
                            Label = "Connaissance des produits financiers, des produits de marchés, de l'organisation d'une BFI",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Dispose d'une connaissance approfondie du monde bancaire et une connaissance générale des opérations de marché et de financement en général.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Dispose d'une connaissance approfondie du monde bancaire et une bonne connaissance des opérations de marché et de financement en général."
                        },
                        new
                        {
                            SkillId = 12,
                            CategoryId = 1,
                            Code = "FCT-PRODUITS-FIN",
                            CriticalityLevel = "P1",
                            FirstLevelDescription = "Dispose d'une connaissance théorique du domaine bancaire. Possède des notions théoriques sur les principaux concepts métiers et leur vocabulaire.",
                            FourthLevelDescription = "Dispose d'une connaissance approfondie du monde bancaire et une connaissance détaillée des opérations de marché et de financement.",
                            Label = "Connaissance des produits financiers, des produits de marchés, de l'organisation d'une BFI",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Dispose d'une connaissance approfondie du monde bancaire et une connaissance générale des opérations de marché et de financement en général.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Dispose d'une connaissance approfondie du monde bancaire et une bonne connaissance des opérations de marché et de financement en général."
                        },
                        new
                        {
                            SkillId = 13,
                            CategoryId = 1,
                            Code = "FCT-RAPPROCHEMENTS",
                            CriticalityLevel = "P2",
                            FirstLevelDescription = "Dispose d'une connaissance théorique des rapprochements comptables dans une banque.",
                            FourthLevelDescription = "Sait faire le lien entre les fonctionnalités des outils applicatifs et les processus de rapprochement de la Direction Financière de CACIB CN1 & CN2.",
                            Label = "Connaissance des Rapprochements Finance de CACIB et de son architecture (fonctionnelle et applicative)",
                            ProjectRequiresSkill = true,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Connait l'architecture applicative des systèmes de rapprochement de CACIB.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Connait les fonctionnalités assurées par les différents composants applicatifs (Intellimatch et EasyMatch) des systèmes de rapprochements."
                        },
                        new
                        {
                            SkillId = 14,
                            CategoryId = 1,
                            Code = "FCT-REGLEMENTAIRE",
                            CriticalityLevel = "P1",
                            FirstLevelDescription = "Connaissance de l'environnement réglementaire & prudentiel propre aux établissements financiers. Possède des notions théoriques sur les principaux concepts métiers et leur vocabulaire.",
                            FourthLevelDescription = "Connaissance avec précision des publications et de l'environnement de contrôle réglementaire prudentiel et peut évoluer en toute autonomie sur le sujet. Peut être considéré expert et mener une réflexion structurante chez le client.",
                            Label = "Connaissance Réglementaire et Reportings Financiers : Attributs réglementaires",
                            ProjectRequiresSkill = false,
                            RequiredLevel = 2,
                            SecondLevelDescription = "Connaissance de l'environnement/contexte réglementaire & prudentiel et a une expérience en lien avec cet environnement.",
                            SubCategoryId = 1,
                            ThirdLevelDescription = "Connaissance de manière très précise l'environnement/contexte réglementaire & prudentiel et a une expérience en lien avec cet environnement."
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            SubCategoryId = 1,
                            CategoryId = 1,
                            Name = "Finance"
                        },
                        new
                        {
                            SubCategoryId = 2,
                            CategoryId = 2,
                            Name = "Cadrage"
                        },
                        new
                        {
                            SubCategoryId = 3,
                            CategoryId = 2,
                            Name = "Design"
                        },
                        new
                        {
                            SubCategoryId = 4,
                            CategoryId = 2,
                            Name = "Design fonctionnel"
                        },
                        new
                        {
                            SubCategoryId = 5,
                            CategoryId = 2,
                            Name = "Design technique"
                        },
                        new
                        {
                            SubCategoryId = 6,
                            CategoryId = 2,
                            Name = "Data"
                        },
                        new
                        {
                            SubCategoryId = 7,
                            CategoryId = 2,
                            Name = "Analyse"
                        },
                        new
                        {
                            SubCategoryId = 8,
                            CategoryId = 2,
                            Name = "Testing"
                        },
                        new
                        {
                            SubCategoryId = 9,
                            CategoryId = 2,
                            Name = "Sécurité"
                        },
                        new
                        {
                            SubCategoryId = 10,
                            CategoryId = 3,
                            Name = "Outil Compta"
                        },
                        new
                        {
                            SubCategoryId = 11,
                            CategoryId = 3,
                            Name = "Outil CdG"
                        },
                        new
                        {
                            SubCategoryId = 12,
                            CategoryId = 3,
                            Name = "Outil Compta reglementaire"
                        },
                        new
                        {
                            SubCategoryId = 13,
                            CategoryId = 3,
                            Name = "Outil Conso"
                        },
                        new
                        {
                            SubCategoryId = 14,
                            CategoryId = 3,
                            Name = "Interprétation comptable"
                        },
                        new
                        {
                            SubCategoryId = 15,
                            CategoryId = 3,
                            Name = "Rapprochements"
                        },
                        new
                        {
                            SubCategoryId = 16,
                            CategoryId = 3,
                            Name = "Technique"
                        },
                        new
                        {
                            SubCategoryId = 17,
                            CategoryId = 4,
                            Name = "Langage de programmation"
                        },
                        new
                        {
                            SubCategoryId = 18,
                            CategoryId = 4,
                            Name = "Transfert de fichiers"
                        },
                        new
                        {
                            SubCategoryId = 19,
                            CategoryId = 4,
                            Name = "CI/CD"
                        },
                        new
                        {
                            SubCategoryId = 20,
                            CategoryId = 4,
                            Name = "Frameworks .NET"
                        },
                        new
                        {
                            SubCategoryId = 21,
                            CategoryId = 4,
                            Name = "Conso"
                        },
                        new
                        {
                            SubCategoryId = 22,
                            CategoryId = 4,
                            Name = "Scripting"
                        },
                        new
                        {
                            SubCategoryId = 23,
                            CategoryId = 4,
                            Name = "Front-End"
                        },
                        new
                        {
                            SubCategoryId = 24,
                            CategoryId = 4,
                            Name = "Middleware"
                        },
                        new
                        {
                            SubCategoryId = 25,
                            CategoryId = 4,
                            Name = "Gestion du code"
                        },
                        new
                        {
                            SubCategoryId = 26,
                            CategoryId = 4,
                            Name = "Base de données"
                        },
                        new
                        {
                            SubCategoryId = 27,
                            CategoryId = 4,
                            Name = "Testing"
                        },
                        new
                        {
                            SubCategoryId = 28,
                            CategoryId = 4,
                            Name = "Sécurité"
                        },
                        new
                        {
                            SubCategoryId = 29,
                            CategoryId = 4,
                            Name = "OS"
                        },
                        new
                        {
                            SubCategoryId = 30,
                            CategoryId = 4,
                            Name = "ETL"
                        },
                        new
                        {
                            SubCategoryId = 31,
                            CategoryId = 4,
                            Name = "Supervision / Monitoring"
                        },
                        new
                        {
                            SubCategoryId = 32,
                            CategoryId = 4,
                            Name = "Paramétrage progiciel"
                        },
                        new
                        {
                            SubCategoryId = 33,
                            CategoryId = 6,
                            Name = "Communication"
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Eid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Eid")
                        .IsUnique();

                    b.HasIndex("RefId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UtCode")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            DeliveryType = "Onshore",
                            Domain = "DIR",
                            Eid = "vithal.seetah",
                            FirstName = "Vitthal",
                            LastName = "Seetah",
                            RefId = "Rf001",
                            RoleId = 1,
                            Status = "Active",
                            UtCode = "UT002"
                        },
                        new
                        {
                            UserId = 1,
                            DeliveryType = "Onshore",
                            Domain = "DIR",
                            Eid = "girish.s.jagroop",
                            FirstName = "Girish",
                            LastName = "Jagroop",
                            RefId = "Rf002",
                            RoleId = 1,
                            Status = "Active",
                            UtCode = "UT003"
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "TechLead"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserSME", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId", "CategoryTypeId");

                    b.HasIndex("CategoryTypeId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSMEs", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserSkill", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("LevelId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills", (string)null);
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Application", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Category", "Category")
                        .WithMany("Applications")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.ApplicationSuite", "ApplicationSuite")
                        .WithMany("Applications")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationSuite");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.ApplicationSkill", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Application", "Application")
                        .WithMany("ApplicationSkills")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.Skill", "Skill")
                        .WithMany("ApplicationSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Category", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.CategoryType", "CategoryType")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryType");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Skill", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Category", "Category")
                        .WithMany("Skills")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.SubCategory", "SubCategory")
                        .WithMany("Skills")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.SubCategory", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.User", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserSME", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.CategoryType", "CategoryType")
                        .WithMany()
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.Skill", "Skill")
                        .WithMany("UserSMEs")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.User", "User")
                        .WithMany("UserSMEs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryType");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("SkillManager.Domain.Entities.Level", "Level")
                        .WithMany("UserSkills")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillManager.Domain.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Application", b =>
                {
                    b.Navigation("ApplicationSkills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.ApplicationSuite", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Category", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Skills");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.CategoryType", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Level", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.Skill", b =>
                {
                    b.Navigation("ApplicationSkills");

                    b.Navigation("UserSMEs");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.SubCategory", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.User", b =>
                {
                    b.Navigation("UserSMEs");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SkillManager.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
