using System.Security.Claims;
using ClosedXML.Excel; // Add this for Excel export
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SkillManager.Application.DTOs;
using SkillManager.Application.Interfaces.Services;
using SkillManager.Domain.Entities;
using SkillManager.Infrastructure.DTOs.Skill;

namespace SkillManager.web.Pages.TeamLeadDashboard.Team
{
    // [Authorize(Policy = "TeamLeadPolicy")]
    public class IndexModel : PageModel
    {
        private readonly IUserService _userService;
        private readonly IUserSkillService _userSkillService;

        public IndexModel(IUserService userService, IUserSkillService userSkillService)
        {
            _userService = userService;
            _userSkillService = userSkillService;
        }

        // Properties
        public List<UserSummary> UserSummaries { get; set; } = new();

        public List<UserSkillDto> TeamMembers { get; set; } = new();
        public List<UserSkillDto> FilteredTeamMembers { get; set; } = new();
        public string TeamLeadName { get; set; } = "";
        public string TeamName { get; set; } = "";
        public int TotalTeamSkills { get; set; }
        public double TeamAverageLevel { get; set; }
        public DateTime? LastTeamUpdate { get; set; }
        public int UniqueTeamMembers =>
            FilteredTeamMembers.Select(t => t.UserId).Distinct().Count();

        // Filtering & Sorting Properties
        [BindProperty(SupportsGet = true)]
        public string? SelectedUser { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? SelectedCategory { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? SelectedSkill { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? SelectedLevel { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? SortBy { get; set; }

        // Add this property for export functionality
        [BindProperty(SupportsGet = true)]
        public string? Handler { get; set; }

        // Available options for filters
        public List<string> AvailableUsers =>
            TeamMembers.Select(t => $"{t.UserId}-{t.FirstName} {t.LastName}").Distinct().ToList();
        public List<string> AvailableCategories =>
            TeamMembers.Select(t => t.CategoryName).Distinct().ToList();
        public List<string> AvailableSkills =>
            TeamMembers.Select(t => t.SkillName).Distinct().ToList();
        public List<string> AvailableLevels => new() { "Notion", "Pratique", "Maitrise", "Expert" };

        public async Task OnGetAsync()
        {
            // Get current team lead info
            var currentUserId = GetCurrentUserId();
            if (currentUserId > 0)
            {
                var currentUser = await _userService.GetByIdAsync(currentUserId);
                TeamLeadName = $"{currentUser.FirstName} {currentUser.LastName}";
                TeamName = currentUser.TeamName ?? "My Team";

                // Get all team members using GetAllByTeamAsync
                TeamMembers = (
                    await _userSkillService.GetAllUserSkillsByTeamAsync(currentUserId)
                ).ToList();

                // Apply filters
                ApplyFilters();

                // Apply sorting
                ApplySorting();

                // Calculate team statistics
                CalculateStatistics();
            }
        }

        public async Task<IActionResult> OnGetExportAsync()
        {
            Console.WriteLine("Excel export function launched for Team Skills");

            // Load the same data as in OnGetAsync
            var currentUserId = GetCurrentUserId();
            if (currentUserId > 0)
            {
                var currentUser = await _userService.GetByIdAsync(currentUserId);
                TeamLeadName = $"{currentUser.FirstName} {currentUser.LastName}";
                TeamName = currentUser.TeamName ?? "My Team";

                TeamMembers = (
                    await _userSkillService.GetAllUserSkillsByTeamAsync(currentUserId)
                ).ToList();

                ApplyFilters();
                CalculateStatistics();
            }

            // Generate Excel
            using var workbook = new XLWorkbook();
            var ws = workbook.Worksheets.Add("TeamSkills");

            // Add title
            ws.Cell(1, 1).Value = $"Team Skills Report - {DateTime.Now:yyyy-MM-dd}";
            ws.Cell(1, 1).Style.Font.Bold = true;
            ws.Cell(1, 1).Style.Font.FontSize = 16;
            ws.Range(1, 1, 1, 11).Merge();

            // Add filters info
            ws.Cell(2, 1).Value = $"Team: {TeamName}";
            ws.Cell(3, 1).Value = $"Generated By: {TeamLeadName}";
            ws.Cell(4, 1).Value = $"User Filter: {SelectedUser ?? "All"}";
            ws.Cell(5, 1).Value = $"Category Filter: {SelectedCategory ?? "All"}";
            ws.Cell(6, 1).Value = $"Skill Filter: {SelectedSkill ?? "All"}";
            ws.Cell(7, 1).Value = $"Level Filter: {SelectedLevel ?? "All"}";

            // Headers starting from row 9
            int headerRow = 9;
            ws.Cell(headerRow, 1).Value = "User ID";
            ws.Cell(headerRow, 2).Value = "First Name";
            ws.Cell(headerRow, 3).Value = "Last Name";
            ws.Cell(headerRow, 4).Value = "Skill ID";
            ws.Cell(headerRow, 5).Value = "Skill Code";
            ws.Cell(headerRow, 6).Value = "Skill Name";
            ws.Cell(headerRow, 7).Value = "Category";
            ws.Cell(headerRow, 8).Value = "Level";
            ws.Cell(headerRow, 9).Value = "Level Points";
            ws.Cell(headerRow, 10).Value = "Last Updated";
            ws.Cell(headerRow, 11).Value = "Days Since Update";

            // Style headers
            var headerRange = ws.Range(headerRow, 1, headerRow, 11);
            headerRange.Style.Font.Bold = true;
            headerRange.Style.Fill.BackgroundColor = XLColor.LightGray;
            headerRange.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

            // Data rows
            int row = headerRow + 1;
            foreach (var skill in FilteredTeamMembers)
            {
                ws.Cell(row, 1).Value = skill.UserId;
                ws.Cell(row, 2).Value = skill.FirstName;
                ws.Cell(row, 3).Value = skill.LastName;
                ws.Cell(row, 4).Value = skill.SkillId;
                ws.Cell(row, 5).Value = skill.SkillCode;
                ws.Cell(row, 6).Value = skill.SkillName;
                ws.Cell(row, 7).Value = skill.CategoryName;
                ws.Cell(row, 8).Value = skill.LevelName;
                ws.Cell(row, 9).Value = skill.LevelId;
                ws.Cell(row, 10).Value = skill.UpdatedTime.ToString("yyyy-MM-dd HH:mm");
                ws.Cell(row, 11).Value = (int)(DateTime.Now - skill.UpdatedTime).TotalDays;
                row++;
            }

            // Add summary statistics
            int summaryRow = row + 2;
            ws.Cell(summaryRow, 1).Value = "Summary Statistics";
            ws.Cell(summaryRow, 1).Style.Font.Bold = true;
            ws.Cell(summaryRow, 1).Style.Font.FontSize = 14;

            ws.Cell(summaryRow + 1, 1).Value = "Total Team Members:";
            ws.Cell(summaryRow + 1, 2).Value = UniqueTeamMembers;

            ws.Cell(summaryRow + 2, 1).Value = "Total Skills:";
            ws.Cell(summaryRow + 2, 2).Value = TotalTeamSkills;

            ws.Cell(summaryRow + 3, 1).Value = "Average Skill Level:";
            ws.Cell(summaryRow + 3, 2).Value = Math.Round(TeamAverageLevel, 2);

            ws.Cell(summaryRow + 4, 1).Value = "Last Team Update:";
            ws.Cell(summaryRow + 4, 2).Value =
                LastTeamUpdate?.ToString("yyyy-MM-dd HH:mm") ?? "N/A";

            // Format columns
            ws.Columns().AdjustToContents();

            // Create the file stream
            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            stream.Position = 0;

            var fileName = $"TeamSkills_{DateTime.Now:yyyyMMddHHmmss}.xlsx";

            return File(
                stream.ToArray(),
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                fileName
            );
        }

        public async Task<IActionResult> OnPostUpdateSkillLevelAsync(
            int skillId,
            int levelId,
            int userId
        )
        {
            try
            {
                Console.WriteLine($"=== UPDATE SKILL DEBUG ===");
                Console.WriteLine($"UserId: {userId}, SkillId: {skillId}, LevelId: {levelId}");

                var success = await _userSkillService.UpdateSkillAsync(
                    userId,
                    new UpdateUserSkillsDto
                    {
                        SkillId = skillId,
                        LevelId = levelId,
                        UpdatedTime = DateTime.Now,
                    }
                );

                if (success)
                {
                    TempData["SuccessMessage"] = "Skill level updated successfully!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Failed to update skill level.";
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error updating skill: {ex.Message}");
                TempData["ErrorMessage"] = $"Error updating skill level: {ex.Message}";
            }

            // Preserve filter and sort parameters
            return RedirectToPage(
                new
                {
                    SelectedUser = SelectedUser,
                    SelectedCategory = SelectedCategory,
                    SelectedSkill = SelectedSkill,
                    SelectedLevel = SelectedLevel,
                    SortBy = SortBy,
                }
            );
        }

        private void ApplyFilters()
        {
            FilteredTeamMembers = TeamMembers;

            // Filter by User
            if (!string.IsNullOrEmpty(SelectedUser) && SelectedUser != "All")
            {
                if (int.TryParse(SelectedUser.Split('-')[0], out int userId))
                {
                    FilteredTeamMembers = FilteredTeamMembers
                        .Where(us => us.UserId == userId)
                        .ToList();
                }
            }

            // Filter by Category
            if (!string.IsNullOrEmpty(SelectedCategory) && SelectedCategory != "All")
            {
                FilteredTeamMembers = FilteredTeamMembers
                    .Where(us =>
                        us.CategoryName.Equals(SelectedCategory, StringComparison.OrdinalIgnoreCase)
                    )
                    .ToList();
            }

            // Filter by Skill
            if (!string.IsNullOrEmpty(SelectedSkill) && SelectedSkill != "All")
            {
                FilteredTeamMembers = FilteredTeamMembers
                    .Where(us =>
                        us.SkillName.Contains(SelectedSkill, StringComparison.OrdinalIgnoreCase)
                    )
                    .ToList();
            }

            // Filter by Level
            if (!string.IsNullOrEmpty(SelectedLevel) && SelectedLevel != "All")
            {
                FilteredTeamMembers = FilteredTeamMembers
                    .Where(us =>
                        us.LevelName.Equals(SelectedLevel, StringComparison.OrdinalIgnoreCase)
                    )
                    .ToList();
            }
        }

        private void ApplySorting()
        {
            FilteredTeamMembers = SortBy switch
            {
                "UserNameAsc" => FilteredTeamMembers
                    .OrderBy(us => us.FirstName)
                    .ThenBy(us => us.LastName)
                    .ToList(),
                "UserNameDesc" => FilteredTeamMembers
                    .OrderByDescending(us => us.FirstName)
                    .ThenByDescending(us => us.LastName)
                    .ToList(),
                "SkillNameAsc" => FilteredTeamMembers.OrderBy(us => us.SkillName).ToList(),
                "SkillNameDesc" => FilteredTeamMembers
                    .OrderByDescending(us => us.SkillName)
                    .ToList(),
                "CategoryAsc" => FilteredTeamMembers.OrderBy(us => us.CategoryName).ToList(),
                "CategoryDesc" => FilteredTeamMembers
                    .OrderByDescending(us => us.CategoryName)
                    .ToList(),
                "LevelAsc" => FilteredTeamMembers.OrderBy(us => us.LevelId).ToList(),
                "LevelDesc" => FilteredTeamMembers.OrderByDescending(us => us.LevelId).ToList(),
                "UpdatedAsc" => FilteredTeamMembers.OrderBy(us => us.UpdatedTime).ToList(),
                "UpdatedDesc" => FilteredTeamMembers
                    .OrderByDescending(us => us.UpdatedTime)
                    .ToList(),
                _ => FilteredTeamMembers
                    .OrderBy(us => us.FirstName)
                    .ThenBy(us => us.LastName)
                    .ThenBy(us => us.SkillName)
                    .ToList(),
            };
        }

        private void CalculateStatistics()
        {
            if (FilteredTeamMembers.Any())
            {
                var userStats = FilteredTeamMembers
                    .GroupBy(us => us.UserId)
                    .Select(g => new
                    {
                        UserId = g.Key,
                        TotalSkills = g.Count(),
                        AverageLevel = g.Average(us => us.LevelId),
                        LastUpdated = g.Max(us => us.UpdatedTime),
                    })
                    .ToList();

                TotalTeamSkills = FilteredTeamMembers.Count;
                TeamAverageLevel = userStats.Average(u => u.AverageLevel);
                LastTeamUpdate = userStats.Max(u => u.LastUpdated);
            }
            else
            {
                TotalTeamSkills = 0;
                TeamAverageLevel = 0;
                LastTeamUpdate = null;
            }
        }

        private int GetCurrentUserId()
        {
            var uidClaim = User.FindFirst("uid");
            if (uidClaim != null && int.TryParse(uidClaim.Value, out int userId))
            {
                return userId;
            }
            return 0;
        }
    }
}
